name: tugas1
description: A new Flutter application.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.9
  cupertino_icons: 1.0.8
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    
